<a href="https://colab.research.google.com/github/Tulja10/IPL_Data_Analysis_Project/blob/main/IPL_DataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import kagglehub
path = kagglehub.dataset_download("patrickb1912/ipl-complete-dataset-20082020")
print(path)

Using Colab cache for faster access to the 'ipl-complete-dataset-20082020' dataset.
/kaggle/input/ipl-complete-dataset-20082020

In [5]:
import os
os.listdir(path)

['deliveries.csv', 'matches.csv']

In [8]:
import pandas as pd
matches=pd.read_csv('/kaggle/input/ipl-complete-dataset-20082020/matches.csv')
deliveries=pd.read_csv('/kaggle/input/ipl-complete-dataset-20082020/deliveries.csv')

In [9]:
matches.shape
deliveries.shape

matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

1. DATASET UNDERSTANDING

In [10]:
#exploring dataset
matches.shape
matches.head()
matches.tail()
# knowing columns and their dtypes
matches.info()
# mathematical summary of numerical cols
matches.describe()
matches.isnull().sum()
# How many unique seasons, teams and venues are there?
matches.nunique()

deliveries.shape
deliveries.head()
deliveries.tail()
# knowing columns and their dtypes
deliveries.info()
# mathematical summary of numerical cols
deliveries.describe()
deliveries.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   object
 15  dismissal_kind    12950 non-null   object
 16  fielder           9354 non-null    object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

2.DATA CLEANING

In [11]:
matches['team1'].unique() #19
# standardizing team names
def standardize(team):
  if team=='Royal Challengers Bangalore':
    return 'Royal Challengers Bengaluru'
  elif team=='Delhi Daredevils':
    return 'Delhi Capitals'
  elif team=='Deccan Chargers':
    return 'Sunrisers Hyderabad'
  elif team=='Kings XI Punjab':
    return 'Punjab Kings'
  elif team=='Pune Warriors':
    return 'Rising Pune Supergiants'
  elif team=='Rising Pune Supergiant':
    return 'Rising Pune Supergiants'
  elif team=='Gujarat Lions':
    return 'Gujarat Titans'
  else:
    return team

matches['team1']=matches['team1'].apply(standardize)
matches['team2']=matches['team2'].apply(standardize)
matches['winner']=matches['winner'].apply(standardize)

matches['winner'].nunique() # count of teams reduced from 19 to 12

12

2. TEAM ANALYSIS

Which team has played the most matches?

In [12]:
pd.concat([matches['team1'],matches['team2']]).value_counts()

Mumbai Indians                 261
Sunrisers Hyderabad            257
Royal Challengers Bengaluru    255
Delhi Capitals                 252
Kolkata Knight Riders          251
Punjab Kings                   246
Chennai Super Kings            238
Rajasthan Royals               221
Rising Pune Supergiants         76
Gujarat Titans                  75
Lucknow Super Giants            44
Kochi Tuskers Kerala            14
Name: count, dtype: int64

Which teams have won the most matches?

In [13]:
matches['winner'].value_counts()

winner
Mumbai Indians                 144
Chennai Super Kings            138
Kolkata Knight Riders          131
Royal Challengers Bengaluru    123
Sunrisers Hyderabad            117
Delhi Capitals                 115
Punjab Kings                   112
Rajasthan Royals               112
Gujarat Titans                  41
Rising Pune Supergiants         27
Lucknow Super Giants            24
Kochi Tuskers Kerala             6
Name: count, dtype: int64

Which teams have the highest win percentage?

In [14]:
(matches['winner'].value_counts()/(matches['team1'].value_counts()+matches['team2'].value_counts()))*100

Chennai Super Kings            57.983193
Delhi Capitals                 45.634921
Gujarat Titans                 54.666667
Kochi Tuskers Kerala           42.857143
Kolkata Knight Riders          52.191235
Lucknow Super Giants           54.545455
Mumbai Indians                 55.172414
Punjab Kings                   45.528455
Rajasthan Royals               50.678733
Rising Pune Supergiants        35.526316
Royal Challengers Bengaluru    48.235294
Sunrisers Hyderabad            45.525292
Name: count, dtype: float64

Which team have won the most titles?

In [17]:
matches[matches['match_type']=='Final']['winner'].value_counts().head(1)

winner
Mumbai Indians    5
Name: count, dtype: int64

Which teams have the best chasing record?

In [18]:
df=matches[(matches['toss_winner']==matches['winner']) & (matches['toss_decision']=='field') | (matches['toss_winner']!=matches['winner']) & (matches['toss_decision']=='bat')]
df.groupby('winner')['target_runs'].max().sort_values(ascending=False).head(1)

winner
Punjab Kings    262.0
Name: target_runs, dtype: float64

3. TOSS ANALYSIS

Does winning the toss increase chances of winning?

In [19]:
((matches['toss_winner']==matches['winner']).sum()/matches.shape[0])*100

np.float64(35.52511415525114)

How often do teams choose batting vs bowling after winning the toss?

In [20]:
(matches['toss_decision'].value_counts()/len(matches))*100

toss_decision
field    64.292237
bat      35.707763
Name: count, dtype: float64

Which teams benefit most from winning the toss?

In [21]:
matches[matches['toss_winner']==matches['winner']]['winner'].value_counts()

winner
Mumbai Indians                 78
Chennai Super Kings            75
Kolkata Knight Riders          68
Rajasthan Royals               60
Sunrisers Hyderabad            38
Delhi Capitals                 26
Gujarat Titans                 14
Lucknow Super Giants           10
Punjab Kings                    9
Kochi Tuskers Kerala            4
Royal Challengers Bengaluru     4
Rising Pune Supergiants         3
Name: count, dtype: int64

4. BATTING ANALYSIS

Who are the top 10 run scorers in IPL history?

In [22]:
deliveries.groupby('batter')['batsman_runs'].sum().sort_values(ascending=False).head(10)

batter
V Kohli           8014
S Dhawan          6769
RG Sharma         6630
DA Warner         6567
SK Raina          5536
MS Dhoni          5243
AB de Villiers    5181
CH Gayle          4997
RV Uthappa        4954
KD Karthik        4843
Name: batsman_runs, dtype: int64

Which batters have scored the most centuries?

In [23]:
temp=deliveries.groupby(['match_id','batter'])['batsman_runs'].sum().reset_index()
temp[temp['batsman_runs']>=100]['batter'].value_counts().head(10)

batter
V Kohli           8
JC Buttler        7
CH Gayle          6
DA Warner         4
SR Watson         4
KL Rahul          4
Shubman Gill      4
AB de Villiers    3
SV Samson         3
V Sehwag          2
Name: count, dtype: int64

Which batters have scored the most fifties?

In [24]:
temp[temp['batsman_runs']>=50]['batter'].value_counts().head(10)

batter
DA Warner         66
V Kohli           64
S Dhawan          53
RG Sharma         45
AB de Villiers    44
KL Rahul          41
SK Raina          40
CH Gayle          38
F du Plessis      37
G Gambhir         36
Name: count, dtype: int64

Which batters hit the most fours?

In [25]:
tempdf=deliveries[deliveries['batsman_runs']==4]
tempdf.groupby('batter')['batsman_runs'].count().sort_values(ascending=False).head(10)

batter
S Dhawan        768
V Kohli         708
DA Warner       663
RG Sharma       599
SK Raina        506
G Gambhir       492
RV Uthappa      481
AM Rahane       479
KD Karthik      466
F du Plessis    422
Name: batsman_runs, dtype: int64

Which batters hit the most sixes?

In [26]:
tempdf2=deliveries[deliveries['batsman_runs']==6]
tempdf2.groupby('batter')['batsman_runs'].count().sort_values(ascending=False).head(10)

batter
CH Gayle          359
RG Sharma         281
V Kohli           273
AB de Villiers    253
MS Dhoni          252
DA Warner         236
KA Pollard        224
AD Russell        209
SV Samson         206
SK Raina          204
Name: batsman_runs, dtype: int64

Which batters have the highest strike rate?

In [27]:
cond1=deliveries.groupby('batter')['batsman_runs'].sum() #total runs scored by batter
cond2=deliveries.groupby('batter').size() # no of balls played by batter
((cond1/cond2)*100).sort_values(ascending=False).head(10)

batter
L Wood             300.000000
B Stanlake         250.000000
J Fraser-McGurk    220.000000
R Sai Kishore      216.666667
Umar Gul           205.263158
RS Sodhi           200.000000
Shahid Afridi      176.086957
I Malhotra         175.000000
WG Jacks           172.932331
PD Salt            169.610390
dtype: float64

Which batters are most consistent across seasons?

In [28]:
dfd=matches.merge(deliveries,how='inner',left_on='id',right_on='match_id').groupby(['batter','season'])['batsman_runs'].sum().reset_index()
dfd.groupby('batter')['batsman_runs'].std().sort_values().head(10)

batter
CRD Fernando        0.000000
RP Meredith         0.000000
KK Ahmed            0.500000
BB Sran             0.577350
A Singh             0.577350
KK Cooper           0.577350
P Parameswaran      0.707107
BE Hendricks        0.707107
Fazalhaq Farooqi    0.707107
BAW Mendis          1.000000
Name: batsman_runs, dtype: float64

5. BOWLING ANALYSIS

Who are the highest wicket takers?

In [29]:
deliveries.groupby('bowler')['is_wicket'].sum().sort_values(ascending=False).head(10)
# OR
deliveries[deliveries['is_wicket']==1].groupby('bowler').size()

bowler
A Ashish Reddy     19
A Badoni            2
A Chandila         11
A Choudhary         5
A Flintoff          2
                 ...
Yash Dayal         31
Yash Thakur        27
Yudhvir Singh       4
Yuvraj Singh       39
Z Khan            119
Length: 455, dtype: int64

Which bowlers bowl the most dot balls?

In [30]:
deliveries[deliveries['total_runs']==0].groupby('bowler').size().sort_values(ascending=False).head(10)

bowler
B Kumar            1632
SP Narine          1569
R Ashwin           1552
PP Chawla          1325
Harbhajan Singh    1263
JJ Bumrah          1228
RA Jadeja          1216
YS Chahal          1194
UT Yadav           1186
A Mishra           1185
dtype: int64

Which bowlers concede the fewest runs based on number of balls he bowled?

In [31]:
bowler_stats=deliveries.groupby('bowler').agg({'total_runs':'sum',
                                  'ball':'count'})
bowler_stats=bowler_stats[bowler_stats['ball']>=300] #considering only regular bowlers who played bowled atleast 300 balls
bowler_stats.sort_values(['total_runs','ball'],ascending=[True,True])

                total_runs  ball
bowler
AD Mascarenhas         365   310
GD McGrath             366   329
ST Jayasuriya          396   301
BA Bhatt               408   303
AC Thomas              416   327
...                    ...   ...
YS Chahal             4681  3628
RA Jadeja             4917  3895
B Kumar               5051  4060
PP Chawla             5179  3895
R Ashwin              5435  4679

[196 rows x 2 columns]

Which bowlers have the best economy rate?

In [32]:
(bowler_stats['total_runs']/(bowler_stats['ball']/6)).sort_values().head(25)

bowler
A Kumble            6.646999
GD McGrath          6.674772
M Muralitharan      6.698292
J Yadav             6.738693
SP Narine           6.761216
RE van der Merwe    6.791209
DW Steyn            6.791411
DL Vettori          6.833121
Rashid Khan         6.907963
J Botha             6.922426
MJ Santner          6.940541
R Ashwin            6.969438
MM Ali              7.012987
SL Malinga          7.032952
Harbhajan Singh     7.038330
R Sharma            7.058824
AD Mascarenhas      7.064516
DP Nannes           7.097242
Iqbal Abdulla       7.158006
DE Bollinger        7.160000
SK Warne            7.187244
M Kartik            7.197970
JJ Bumrah           7.233909
MF Maharoof         7.238095
Ankit Sharma        7.248000
dtype: float64

Which bowlers have the best bowling strike rate?

In [33]:
(bowler_stats['ball']/deliveries[deliveries['is_wicket']==1].groupby('bowler').size()).sort_values()

bowler
L Ngidi            12.214286
M Pathirana        13.236842
MF Maharoof        13.363636
Mukesh Kumar       13.548387
DE Bollinger       13.953488
                     ...
Y Nagar                  NaN
Y Prithvi Raj            NaN
Y Venugopal Rao          NaN
YA Abdulla               NaN
Yudhvir Singh            NaN
Length: 455, dtype: float64